### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by DarkGD123** [BlissSc/GDPSDiscordBotJS#1]
When i was setting up node.js and did the ```npm install``` command it listed this errors

npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../mime/cli.js
npm ERR! dest /storage/emulated/0/GDPSstuff/GDPSDiscordBotJS-master/node_modules/.bin/mime
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/storage/emulated/0/GDPSstuff/GDPSDiscordBotJS-master/node_modules/.bin/mime'
npm ERR!  [OperationalError: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/storage/emulated/0/GDPSstuff/GDPSDiscordBotJS-master/node_modules/.bin/mime'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, symlink '../mime/cli.js' -> '/storage/emulated/0/GDPSstuff/GDPSDiscordBotJS-master/node_modules/.bin/mime'] {
npm ERR!     errno: -1,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../mime/cli.js',
npm ERR!     dest: '/storage/emulated/0/GDPSstuff/GDPSDiscordBotJS-master/node_modules/.bin/mime'
npm ERR!   },
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../mime/cli.js',
npm ERR!   dest: '/storage/emulated/0/GDPSstuff/GDPSDiscordBotJS-master/node_modules/.bin/mime',
npm ERR!   parent: 'GDPSDiscordBotJS-master'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by RXNationGMG** [comment]
Yea I got that error!
